/**
 * S1.6 — shareable review artifact (markdown / HTML), a SANCTIONED render
 * module of the S1.9 choke point (tests/sanitize.test.ts guard).
 *
 * Two NEW escaping contexts beyond the terminal (norm 9):
 *
 *  - Markdown: the choke point already strips newlines (U+000A is inside the
 *    C0 range U+0000–U+001F), so no field can open a new line — heading and
 *    verdict forgery via embedded line breaks is impossible after the
 *    choke-point sanitizers (sanitizeField / sanitizeFieldKeepEnding — same
 *    strip set, S1.12). Markdown METAcharacters survive the strip set, though
 *    (`[`, `](…)`, `#`, `!`, `<`…), so every workspace-derived field is
 *    rendered inside a GFM code SPAN (mdCode below): link/image injection
 *    (`[x](javascript:…)`, `![x](…)`) and inline HTML are inert literal text
 *    inside a code span. Fields never start a line — every interpolation
 *    sits after a static prefix — so a field of backticks cannot open a
 *    fenced block either.
 *
 *  - HTML: every interpolated field passes the choke point AND escapeHtml
 *    (&, <, >, ", ' — ampersand first, so escaping is single-pass and never
 *    double-encodes). The artifact is self-contained: no scripts, no anchor
 *    tags, no external resources, no dynamic attributes — workspace content
 *    only ever lands in TEXT positions, already escaped.
 *
 * Copy rules: external audience only (shareable in a PR/channel) — no
 * internal document pointers; terminology per the glossary ("review",
 * "boundary gap" — never scan/vulnerability).
 *
 * Determinism: byte-identical for identical inputs; the caller-supplied
 * `generatedAt` appears on exactly ONE line per format, so two runs over the
 * same workspace differ only on the timestamp line.
 */
import { readFileSync } from "node:fs";
import { BASELINE_REL_PATH } from "./baseline.js";
import { claimedIdentityClaim } from "./identity.js";
import { factorLine, POSTURE_ASSURANCE_NOTE, POSTURE_HONEST_LIMIT_NOTE, qualifiedPostureLine, } from "./score.js";
import { OUTCOME_LABEL, policyRefLabel } from "./evaluate.js";
import { SEV_LABEL } from "./report.js";
import { sanitizeField, sanitizeFieldKeepEnding } from "./sanitize.js";
import { countNoun } from "./text.js";
/**
 * ADR-005 no-positive-assurance copy for identity: claimed-tier records are
 * self-asserted workspace metadata, never authenticated.
 */
const IDENTITY_DISCLAIMER = "Identities are claims derived from workspace configuration (attestation: claimed) — " +
    "not verified.";
/**
 * ADR-003 threat-note mitigations 1+2 (same phrasing convention as the text
 * report's renderBaselineSection): the absence of drift findings is NEVER
 * positive assurance — the baseline is agent-writable.
 */
const NO_POSITIVE_ASSURANCE = "No drift detected against the local baseline. The baseline is agent-writable — " +
    "this is not positive assurance; verify the provenance above.";
// TEAM-ADR-027: the next action is the Governance Studio, never a terminal
// command. External-audience copy only — user-visible benefit, no internals.
const FOOTER = "Generated by DeepSweep — Agent Environment Review. Open the Governance Studio on any " +
    "workspace to see what your AI coding agents can currently do and which protections are missing.";
/**
 * Tool version, read from this package's own package.json at runtime (the
 * boring way: no build-step stamping, no extra dependency). The path is the
 * same relative hop from src/review/ (dev, tsx) and dist/review/ (built):
 * two levels up is the package root. Never throws — an unreadable manifest
 * degrades to "unknown".
 */
export function toolVersion() {
    try {
        const raw = readFileSync(new URL("../../package.json", import.meta.url), "utf8");
        const pkg = JSON.parse(raw);
        return typeof pkg.version === "string" && pkg.version !== "" ? pkg.version : "unknown";
    }
    catch {
        return "unknown";
    }
}
/** Dispatcher the CLI writes through (per-write-site guard recognizes it). */
export function renderArtifact(input, format) {
    return format === "md" ? renderMarkdownArtifact(input) : renderHtmlArtifact(input);
}
/** Count-agreeing "N capability/capabilities" for the authorization section. */
function authCaps(n) {
    return countNoun(n, "capability", "capabilities");
}
// ---------------------------------------------------------------- markdown
/**
 * GFM code span over already-sanitized content. Fence length exceeds the
 * longest backtick run in the content; space padding when the content
 * starts/ends with a backtick (GFM strips one symmetric pad). Never emitted
 * at start-of-line by the renderer below, so it cannot open a fenced code
 * block.
 */
function mdSpan(content) {
    const c = content === "" ? " " : content;
    const runs = c.match(/`+/g) ?? [];
    const fence = "`".repeat(runs.reduce((max, r) => Math.max(max, r.length), 0) + 1);
    const pad = c.startsWith("`") || c.endsWith("`") ? " " : "";
    return `${fence}${pad}${c}${pad}${fence}`;
}
/** Choke point + GFM code span. */
function mdCode(raw) {
    return mdSpan(sanitizeField(raw));
}
/**
 * Keep-ending choke-point variant + GFM code span (S1.12): finding
 * explanations, warning summaries, and trust factor lines carry their
 * remediation/disclosure at the END — same treatment as the text report and
 * watch surfaces, same single choke point.
 */
function mdCodeKeepEnding(raw) {
    return mdSpan(sanitizeFieldKeepEnding(raw));
}
export function renderMarkdownArtifact(input) {
    const r = input.report;
    const p = input.provenance;
    const lines = [];
    lines.push("# DeepSweep — Agent Environment Review");
    lines.push("");
    lines.push(`Reviewed at: ${mdCode(input.generatedAt)}`);
    lines.push(`Tool: DeepSweep Review ${mdCode(input.toolVersion)}`);
    lines.push("");
    lines.push("## Agent capabilities");
    lines.push("");
    if (r.capabilities.length === 0) {
        lines.push("No agent capabilities detected in this workspace.");
        lines.push("");
        lines.push(`Sources reviewed: ${r.reviewedSources.length ? r.reviewedSources.map(mdCode).join(", ") : "none found"}`);
    }
    else {
        lines.push("Your AI agents currently have:");
        lines.push("");
        for (const c of r.capabilities) {
            lines.push(`- ${mdCode(c.summary)} — source: ${mdCode(c.source)}`);
        }
    }
    if (input.identity !== undefined) {
        lines.push("");
        lines.push("## Agent identity (claimed)");
        lines.push("");
        lines.push(IDENTITY_DISCLAIMER);
        lines.push("");
        if (input.identity.length === 0) {
            lines.push("No agent config surfaces observed — nothing to attribute in this workspace.");
        }
        else {
            for (const a of input.identity) {
                lines.push(`- ${mdCode(a.agentId)} — ${mdCode(claimedIdentityClaim(a.agentType))} — first observed ${mdCode(a.firstObservedAt)} — attestation: ${mdCode(a.attestation)}`);
            }
        }
    }
    if (input.trust !== undefined) {
        lines.push("");
        lines.push("## Trust score (posture)");
        lines.push("");
        lines.push(POSTURE_ASSURANCE_NOTE);
        lines.push("");
        lines.push(POSTURE_HONEST_LIMIT_NOTE);
        lines.push("");
        if (input.trust.length === 0) {
            lines.push("No attributed agent identities to score in this workspace.");
        }
        else {
            for (const t of input.trust) {
                lines.push(`- ${mdCode(t.agentId)} — ${mdCode(claimedIdentityClaim(t.agentType))} — ${mdCode(qualifiedPostureLine(t.trustScore))} (scoreVersion ${t.trustScore.scoreVersion})`);
                for (const f of t.trustScore.decomposition) {
                    lines.push(`  - ${mdCodeKeepEnding(factorLine(f))}`);
                }
            }
        }
    }
    if (input.authorization !== undefined) {
        const a = input.authorization;
        lines.push("");
        lines.push("## Authorization coverage");
        lines.push("");
        if (a.totalCapabilities === 0) {
            lines.push("No agent capabilities detected — nothing to govern yet.");
        }
        else if (a.policyStatus === "absent") {
            lines.push(`${authCaps(a.totalCapabilities)} detected, 0 governed by policy — no ${mdCode(a.policyFile)} yet. DeepSweep sees what your agents CAN do; no policy yet says whether it is allowed.`);
        }
        else if (a.policyStatus === "invalid") {
            lines.push(`Policy was refused (see the policy.invalid finding) — no rule is evaluated, so all ${authCaps(a.totalCapabilities)} are authorization gaps until it is fixed.`);
        }
        else {
            lines.push(`${a.governed} of ${authCaps(a.totalCapabilities)} governed by policy · ${countNoun(a.gaps.length, "authorization gap", "authorization gaps")}.`);
            if (a.gaps.length > 0) {
                lines.push("");
                for (const g of a.gaps) {
                    lines.push(`- **GAP** ${mdCode(g.summary)} — action ${mdCode(g.action)}, resource ${mdCode(g.resource)} (source: ${mdCode(g.source)}): no policy rule names this capability.`);
                }
            }
        }
    }
    if (input.decisions !== undefined) {
        const d = input.decisions;
        lines.push("");
        lines.push("## Policy decisions (advisory)");
        lines.push("");
        lines.push("Most-restrictive-wins over `.deepsweep/policy.json` — never enforced, never a grant (`observe` is record-only).");
        lines.push("");
        if (d.policyStatus !== "present" || d.decisions.length === 0) {
            lines.push("No committed policy governs any capability yet — see authorization coverage above.");
        }
        else {
            for (const cd of d.decisions) {
                const dec = cd.decision;
                if (dec.matchedRules.length === 0) {
                    lines.push(`- **${OUTCOME_LABEL[dec.outcome]}** ${mdCode(cd.summary)} — action ${mdCode(dec.action)}, resource ${mdCode(dec.resource)}: governed, but no rule applies to this principal/condition — defaults to observe (record-only).`);
                    continue;
                }
                const matched = dec.matchedRules.map((m) => mdCode(policyRefLabel(m.policyRef))).join(", ");
                lines.push(`- **${OUTCOME_LABEL[dec.outcome]}** ${mdCode(cd.summary)} — action ${mdCode(dec.action)}, resource ${mdCode(dec.resource)}: decided by ${mdCode(policyRefLabel(dec.policyRef))}; matched ${matched}. ${mdCodeKeepEnding(dec.explanation)}`);
            }
        }
    }
    lines.push("");
    lines.push("## Boundary gaps");
    lines.push("");
    lines.push(`Boundary gaps found: ${r.totals.boundaryGaps} (${r.totals.critical} critical, ${r.totals.high} high)`);
    if (r.boundaryGaps.length > 0) {
        lines.push("");
        for (const g of r.boundaryGaps) {
            lines.push(`- **${SEV_LABEL[g.severity]}** — ${mdCode(g.summary)}`);
            lines.push(`  - Recommended protection: ${mdCode(g.recommendation)}`);
        }
    }
    if (r.warnings.length > 0) {
        lines.push("");
        lines.push("## Review warnings");
        lines.push("");
        for (const w of r.warnings) {
            lines.push(`- ${mdCode(w.source)} — ${mdCodeKeepEnding(w.summary)}`);
        }
    }
    lines.push("");
    lines.push("## Baseline provenance");
    lines.push("");
    lines.push(`Local baseline (${mdCode(BASELINE_REL_PATH)}) — stored in the workspace and agent-writable.`);
    lines.push("");
    lines.push(`- Pinned entities: ${p.entityCount}`);
    lines.push(`- Created: ${mdCode(p.createdAt)}`);
    lines.push(`- Last pinned: ${mdCode(p.lastPinnedAt)}`);
    lines.push(`- File sha256 (computed at read time): ${mdCode(p.baselineSha256)}`);
    if (input.repinned) {
        lines.push("- Baseline explicitly re-pinned this run (`--update-baseline`).");
    }
    const { lifecycle, drift } = splitFindings(input.findings);
    if (lifecycle.length > 0) {
        lines.push("");
        for (const f of lifecycle) {
            lines.push(`- **${SEV_LABEL[f.severity]}** ${mdCode(f.kind)}: ${mdCodeKeepEnding(f.explanation)}`);
        }
    }
    lines.push("");
    if (drift.length === 0) {
        lines.push(NO_POSITIVE_ASSURANCE);
    }
    else {
        for (const f of drift) {
            lines.push(`- **${SEV_LABEL[f.severity]}** ${mdCode(f.kind)} ${mdCode(f.resource)} — ${mdCodeKeepEnding(f.explanation)}`);
        }
    }
    lines.push("");
    lines.push("---");
    lines.push("");
    lines.push(FOOTER);
    lines.push("");
    return lines.join("\n");
}
// -------------------------------------------------------------------- html
/**
 * Single-pass HTML escape (ampersand FIRST — no double-encoding). Applied on
 * top of the choke point to every interpolated field; fields only ever land
 * in text positions (no dynamic attributes exist in this template).
 */
function escapeHtml(value) {
    return value
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#39;");
}
/** Choke point + HTML escaping — the only path a field takes into the page. */
function h(raw) {
    return escapeHtml(sanitizeField(raw));
}
function hCode(raw) {
    return `<code>${h(raw)}</code>`;
}
/** Keep-ending choke-point variant + HTML escaping (S1.12 — see mdCodeKeepEnding). */
function hCodeKeepEnding(raw) {
    return `<code>${escapeHtml(sanitizeFieldKeepEnding(raw))}</code>`;
}
export function renderHtmlArtifact(input) {
    const r = input.report;
    const p = input.provenance;
    const lines = [];
    lines.push("<!doctype html>");
    lines.push('<html lang="en">');
    lines.push("<head>");
    lines.push('<meta charset="utf-8">');
    lines.push("<title>DeepSweep — Agent Environment Review</title>");
    lines.push("<style>");
    lines.push("body{font-family:system-ui,sans-serif;max-width:46rem;margin:2rem auto;padding:0 1rem;color:#1b1b1b}");
    lines.push("code{background:#f2f2f2;padding:.1em .3em;border-radius:3px;word-break:break-all}");
    lines.push("li{margin:.25em 0}");
    lines.push("hr{border:none;border-top:1px solid #ddd;margin:2rem 0}");
    lines.push("</style>");
    lines.push("</head>");
    lines.push("<body>");
    lines.push("<h1>DeepSweep — Agent Environment Review</h1>");
    lines.push(`<p>Reviewed at: ${hCode(input.generatedAt)}</p>`);
    lines.push(`<p>Tool: DeepSweep Review ${hCode(input.toolVersion)}</p>`);
    lines.push("<h2>Agent capabilities</h2>");
    if (r.capabilities.length === 0) {
        lines.push("<p>No agent capabilities detected in this workspace.</p>");
        lines.push(`<p>Sources reviewed: ${r.reviewedSources.length ? r.reviewedSources.map(hCode).join(", ") : "none found"}</p>`);
    }
    else {
        lines.push("<p>Your AI agents currently have:</p>");
        lines.push("<ul>");
        for (const c of r.capabilities) {
            lines.push(`<li>${hCode(c.summary)} — source: ${hCode(c.source)}</li>`);
        }
        lines.push("</ul>");
    }
    if (input.identity !== undefined) {
        lines.push("<h2>Agent identity (claimed)</h2>");
        lines.push(`<p>${escapeHtml(IDENTITY_DISCLAIMER)}</p>`);
        if (input.identity.length === 0) {
            lines.push("<p>No agent config surfaces observed — nothing to attribute in this workspace.</p>");
        }
        else {
            lines.push("<ul>");
            for (const a of input.identity) {
                lines.push(`<li>${hCode(a.agentId)} — ${hCode(claimedIdentityClaim(a.agentType))} — first observed ${hCode(a.firstObservedAt)} — attestation: ${hCode(a.attestation)}</li>`);
            }
            lines.push("</ul>");
        }
    }
    if (input.trust !== undefined) {
        lines.push("<h2>Trust score (posture)</h2>");
        lines.push(`<p>${escapeHtml(POSTURE_ASSURANCE_NOTE)}</p>`);
        lines.push(`<p>${escapeHtml(POSTURE_HONEST_LIMIT_NOTE)}</p>`);
        if (input.trust.length === 0) {
            lines.push("<p>No attributed agent identities to score in this workspace.</p>");
        }
        else {
            lines.push("<ul>");
            for (const t of input.trust) {
                lines.push(`<li>${hCode(t.agentId)} — ${hCode(claimedIdentityClaim(t.agentType))} — ${hCode(qualifiedPostureLine(t.trustScore))} (scoreVersion ${t.trustScore.scoreVersion})`);
                if (t.trustScore.decomposition.length > 0) {
                    lines.push("<ul>");
                    for (const f of t.trustScore.decomposition) {
                        lines.push(`<li>${hCodeKeepEnding(factorLine(f))}</li>`);
                    }
                    lines.push("</ul>");
                }
                lines.push("</li>");
            }
            lines.push("</ul>");
        }
    }
    if (input.authorization !== undefined) {
        const a = input.authorization;
        lines.push("<h2>Authorization coverage</h2>");
        if (a.totalCapabilities === 0) {
            lines.push("<p>No agent capabilities detected — nothing to govern yet.</p>");
        }
        else if (a.policyStatus === "absent") {
            lines.push(`<p>${authCaps(a.totalCapabilities)} detected, 0 governed by policy — no ${hCode(a.policyFile)} yet. DeepSweep sees what your agents CAN do; no policy yet says whether it is allowed.</p>`);
        }
        else if (a.policyStatus === "invalid") {
            lines.push(`<p>Policy was refused (see the policy.invalid finding) — no rule is evaluated, so all ${authCaps(a.totalCapabilities)} are authorization gaps until it is fixed.</p>`);
        }
        else {
            lines.push(`<p>${a.governed} of ${authCaps(a.totalCapabilities)} governed by policy · ${countNoun(a.gaps.length, "authorization gap", "authorization gaps")}.</p>`);
            if (a.gaps.length > 0) {
                lines.push("<ul>");
                for (const g of a.gaps) {
                    lines.push(`<li><strong>GAP</strong> ${hCode(g.summary)} — action ${hCode(g.action)}, resource ${hCode(g.resource)} (source: ${hCode(g.source)}): no policy rule names this capability.</li>`);
                }
                lines.push("</ul>");
            }
        }
    }
    if (input.decisions !== undefined) {
        const d = input.decisions;
        lines.push("<h2>Policy decisions (advisory)</h2>");
        lines.push("<p>Most-restrictive-wins over <code>.deepsweep/policy.json</code> — never enforced, never a grant (<code>observe</code> is record-only).</p>");
        if (d.policyStatus !== "present" || d.decisions.length === 0) {
            lines.push("<p>No committed policy governs any capability yet — see authorization coverage above.</p>");
        }
        else {
            lines.push("<ul>");
            for (const cd of d.decisions) {
                const dec = cd.decision;
                if (dec.matchedRules.length === 0) {
                    lines.push(`<li><strong>${OUTCOME_LABEL[dec.outcome]}</strong> ${hCode(cd.summary)} — action ${hCode(dec.action)}, resource ${hCode(dec.resource)}: governed, but no rule applies to this principal/condition — defaults to observe (record-only).</li>`);
                    continue;
                }
                const matched = dec.matchedRules.map((m) => hCode(policyRefLabel(m.policyRef))).join(", ");
                lines.push(`<li><strong>${OUTCOME_LABEL[dec.outcome]}</strong> ${hCode(cd.summary)} — action ${hCode(dec.action)}, resource ${hCode(dec.resource)}: decided by ${hCode(policyRefLabel(dec.policyRef))}; matched ${matched}. ${hCodeKeepEnding(dec.explanation)}</li>`);
            }
            lines.push("</ul>");
        }
    }
    lines.push("<h2>Boundary gaps</h2>");
    lines.push(`<p>Boundary gaps found: ${r.totals.boundaryGaps} (${r.totals.critical} critical, ${r.totals.high} high)</p>`);
    if (r.boundaryGaps.length > 0) {
        lines.push("<ul>");
        for (const g of r.boundaryGaps) {
            lines.push(`<li><strong>${SEV_LABEL[g.severity]}</strong> — ${hCode(g.summary)}<br>Recommended protection: ${hCode(g.recommendation)}</li>`);
        }
        lines.push("</ul>");
    }
    if (r.warnings.length > 0) {
        lines.push("<h2>Review warnings</h2>");
        lines.push("<ul>");
        for (const w of r.warnings) {
            lines.push(`<li>${hCode(w.source)} — ${hCodeKeepEnding(w.summary)}</li>`);
        }
        lines.push("</ul>");
    }
    lines.push("<h2>Baseline provenance</h2>");
    lines.push(`<p>Local baseline (${hCode(BASELINE_REL_PATH)}) — stored in the workspace and agent-writable.</p>`);
    lines.push("<ul>");
    lines.push(`<li>Pinned entities: ${p.entityCount}</li>`);
    lines.push(`<li>Created: ${hCode(p.createdAt)}</li>`);
    lines.push(`<li>Last pinned: ${hCode(p.lastPinnedAt)}</li>`);
    lines.push(`<li>File sha256 (computed at read time): ${hCode(p.baselineSha256)}</li>`);
    if (input.repinned) {
        lines.push("<li>Baseline explicitly re-pinned this run (<code>--update-baseline</code>).</li>");
    }
    const { lifecycle, drift } = splitFindings(input.findings);
    for (const f of lifecycle) {
        lines.push(`<li><strong>${SEV_LABEL[f.severity]}</strong> ${hCode(f.kind)}: ${hCodeKeepEnding(f.explanation)}</li>`);
    }
    lines.push("</ul>");
    if (drift.length === 0) {
        lines.push(`<p>${escapeHtml(NO_POSITIVE_ASSURANCE)}</p>`);
    }
    else {
        lines.push("<ul>");
        for (const f of drift) {
            lines.push(`<li><strong>${SEV_LABEL[f.severity]}</strong> ${hCode(f.kind)} ${hCode(f.resource)} — ${hCodeKeepEnding(f.explanation)}</li>`);
        }
        lines.push("</ul>");
    }
    lines.push("<hr>");
    lines.push(`<p>${escapeHtml(FOOTER)}</p>`);
    lines.push("</body>");
    lines.push("</html>");
    lines.push("");
    return lines.join("\n");
}
// ------------------------------------------------------------------ shared
function splitFindings(findings) {
    return {
        lifecycle: findings.filter((f) => f.kind !== "pin.drift" && f.kind !== "pin.conflict"),
        drift: findings.filter((f) => f.kind === "pin.drift" || f.kind === "pin.conflict"),
    };
}
